# 测试用例
bash "/storage/emulated/0/001_中转站/fuck-joyose/fuck-joyose.sh"
bash "/storage/emulated/0/Documents/fuck-joyose/fuck-joyose.sh"
bash "/storage/emulated/0/101o5_自用工具/fuck-joyose/fuck-joyose.sh"
sh "/storage/emulated/0/101o5_自用工具/fuck-joyose/fuck-joyose_test.sh"
source "/storage/emulated/0/101o5_自用工具/fuck-joyose/fuck-joyose_test.sh"
cd "/storage/emulated/0/101o5_自用工具/fuck-joyose/"
sh "adb_test.sh"
sh "/storage/emulated/0/101o5_自用工具/fuck-joyose/adb_test.sh"
